apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: alaaissa469/examenalaaissa:v1.0
        ports:
        - containerPort: 8082
